TRANSIENT_STATUS_MS = 4_500
TOAST_DURATION_MS = 3_500
HELP_HOVER_DELAY_MS = 150
HELP_HIDE_DELAY_MS = 360
FORGE_REFRESH_DEBOUNCE_MS = 120
CATALOG_REFRESH_DEBOUNCE_MS = 180
MESSAGE_RENDER_DEBOUNCE_MS = 180
SHUTDOWN_TIMEOUT_MS = 5_000


__all__ = [
    "CATALOG_REFRESH_DEBOUNCE_MS",
    "FORGE_REFRESH_DEBOUNCE_MS",
    "HELP_HIDE_DELAY_MS",
    "HELP_HOVER_DELAY_MS",
    "MESSAGE_RENDER_DEBOUNCE_MS",
    "SHUTDOWN_TIMEOUT_MS",
    "TOAST_DURATION_MS",
    "TRANSIENT_STATUS_MS",
]
